sudo: required
language: node_js

node_js:
  - 12

os:
  - linux

branches:
  except:
    - develop
    - /^feature/\d+\.\d+$/
  only:
    - master

script:
  - yarn
  - yarn coveralls

before_deploy:
  - npm --no-git-tag-version version patch

deploy:
  edge: true
  provider: npm
  email: "enesusta@protonmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true
